### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by guodont** [DigDream/urp-python#2]
```
guodontdeMacBook-Pro:urp-python guodont$ sudo python urpclient.py grade -no 20131612807
Traceback (most recent call last):
  File "urpclient.py", line 4, in <module>
    from utils.handlers.evaluate import evaluate_teacher
  File "/Users/guodont/app/urp-python/utils/handlers/evaluate.py", line 4, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
```

**Comment by dubuqingfeng** [comment]
没安装那个BeautifulSoup呀，这个是个解析库。
